# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17fslQ8yN0jYWDykEZS_kGXFO17M7ZvJy
"""



#print table using while lop#

q=int(input())
i=1
while i <11:
    value=q*i
    print(q,"*",i,"=",value)
    i=i+1

#print table using for loop

o=int(input())
for i in range(1,11):
    print(o,"*",i,"=",o*i)

#username has ten characters or not

p=(input())
a=len(p)
if a>10:
    print("Username has ten characters")
else:
    print("Username has not ten characters")

"""# Program to take 10 numbers input and display only distinct elements#"""

a=[]
n=int(input("enter the number of elements in list "))
for i in range(n):
    a.append(int(input()))
    
c=set(a)
print(c)

#Greet Message=” Congrats name you scored more than 70 ”#

p=input()
o=int(input())
if o>70:
    print("Congrats",p,"You scored more then 70")
else:
    print("Your score is not good")

#Program to calculate sum of elements of list having value less than 10#

x=[]
res=[]
s=int(input("enter the number of integers in list "))
for i in range(s):
    x.append(int(input()))
for i in x:
    if(i<10):
        res.append(i)
        

a=sum(res)
print("Sum of integers whoose value is less then 10 is",a)

#Program to calculate teen ager students in list#

a=[]

result=[]

n=int(input("Enter the Number of students in list" ))

for i in range(n):
  a.append(int(input()))

for i in a:
  if (i>13) and(i<19):
    result.append(i)


print("List of Teenager Students",result)

#Program to store 7 names of your friends entered by User

a=[]
n=int(input("enter the number of students : "))
for i in range(n):
  a.append(int(input()))
  a.sort()
print("Highest makrs",a[-1])

#Program to display User entered name using Input() followed by “Good Afternoon”#

q=input()
print("Good Afternoon",q)

#Program to calculate Square entered by User#

a=int(input())
p=a*a
print(p)

#Program to find the average of two numbers entered by a user#

a=int(input())
b=int(input())

s=a+b
q=s//2

print(q)

#PROGRAM TO PRINT 3RD LARGEST NUMBER IN LIST#

a=[]
n=int(input('ENTER THE NUMBER OF ELEMETS IN LIST'))
for i in range(n):
  a.append(int(input()))
a.sort()

print(a[-3],"Is The Third Largest Value")

#Program who takes input as age and tells whether you are eligible to vote or not#

def age(x):
  if x>18:
    print("You are eligible to vote")
  else:
    print("You are Not eligible to vote ")

age(14)

x=int(input())
age=0
if age>18:
  print("You are eligible")
else:
  print("You are not eligible")

#Program to accept Marks of 10 students entered by user and display them in sorted Way

a=[]
n=int(input("enter the number of students : "))
for i in range(n):
  a.append(int(input()))
  a.sort()
print("Highest makrs",a[-1])

#Program to print table of a number in reversed order

n=int(input("enter the number "))
for i in range(10,0,-1):
  print(n,"*",i,"=",n*i)

#Program to find out whether a student is overall pass or fail. His marks in 5 subjects entered by the user.
To pass in each subject he must score 33%.
To overall pass he must pass in all subjects and total marks in all subjects greater than 40%.
Maximum marks in each subject is 100#

maths=int(input('enter the maths marks '))
if maths>33:
    
    print("Pass in maths")
else:
    print('Fail in maths')

science=int(input('enter the science marks '))
if science>33:
    
    print("Pass in science")
else:
    ("Fail in science")

english=int(input('enter the english marks '))
if english>33:
    
    print("Pass in english")
else:
    print("Fail in english")

physics=int(input('enter the physics marks '))
if physics>33:
    
    print("Pass in physics")
else:
    ("Fail in physics")

chemistry=int(input('enter the chemistry marks '))
if chemistry>33:
    
    print("Pass in chemistry")
else:
    print("Fail in chemistry")
    
z=maths+science+english+physics+chemistry

f=z/500*100

if f>40:
    
    print(f,"%","Student is promoted")
    
else:
    print("Student is fail")

#Program to format below code using escape sequence Characters#

c="Dear Sir Python is very amazing Programming language \n Please share more Questions like this Thank you"
print(c)

#Program to detect double Spaces in a User entered String if yes then replace it with single space#

q=input("enter the string ")
q=q.replace("  "," ")
print("Modified string is:",q)

#Program to calculate sum of first N natural numbers#

num=int(input())
if a<0:
  print("Please enter the positive number")
else:
  sum=0
  while num>0:
    sum +=num
    num -=1
  print(sum)